### ISSUE TITLE
Running prettier adds an extra new line to end of file

### ISSUE THREAD

**Issue by felamaslen** [neoclide/coc-prettier#105]
Say I have a file:

```ts
// myfile.ts
function doSomething(): void {
  console.log('say hello');
}
```

Calling `:CocCommand prettier.formatFile` will result in the file being updated to:

```ts
// myfile.ts
function doSomething(): void {
  console.log('say hello');
}

```

(i.e. with an extra new line at the end).

This breaks eslint for the file. The expected result is no change.

Calling `./node_modules/.bin/prettier myfile.ts` directly, does *not* add the new line.

**Comment by chemzqm** [comment]
Can't reproduce.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by Kasama** [comment]
I'm sorry to bother with this again, but I seem to be running into the same problem.

steps to reproduce:
- backup your `~/.config/nvim` directory
- copy the minimal `init.vim` below to `~/.config/nvim/init.vim`
- open a file `test.js`  (vim will auto install Plug, coc and coc-prettier, close the split it opens afterwards)
- write a line (e.g `console.log("hello");`)
- run `:Prettier`
- coc-prettier will add a new line at the end of the file.

As specified by the original author, running prettier manually does not yield the same result.

`:!./node_modules/.bin/prettier test.js -w`

minimal `init.vim`

```vim
"" Autoinstall Plug
let vimPlugPath = '~/.config/nvim/autoload/plug.vim'

if empty(glob(vimPlugPath))
  silent exe '!curl -fLo' vimPlugPath '--create-dirs'
        \ 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

"" Init Plug
let plugged_path=expand('~/.config/nvim/plugged/')
call plug#begin(plugged_path)

Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install() }}

let g:coc_global_extensions = [ 'coc-prettier' ]

call plug#end()

command! -nargs=0 Prettier :CocCommand prettier.formatFile
```

extra info:

- `prettier --version` => `2.2.1`
- `nvim --version` =>
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by chemzqm** [comment]
Use release branch instead.

**Comment by alecdwm** [comment]
I can still reproduce this bug when I open a file with no newline at the end of it.

Steps:
1. Follow @Kasama's instructions for a minimal vim config, but use the release branch for coc.nvim:
```vim
Plug 'neoclide/coc.nvim', {'branch': 'release'}
```
2. Create a file with no trailing newline (echo appends one by default, -n disables this)
```bash
echo -n 'function testfail() {}' > testfail.js
```
3. Open `testfail.js` in vim and run `:CocCommand prettier.formatFile`. There will be an extra newline:
```javascript
---begin---
function testfail() {}

---end---
```

Whereas if you run `prettier testfail.js > testfail.prettier.js` you'll see that there is no extra newline:
```javascript
---begin---
function testfail() {}
---end---
```

Similarly, opening a file which does already end with a newline will work as expected:
```bash
echo 'function testpass() {}' > testpass.js
vim testpass.js
# run :CocCommand prettier.formatFile
```
```javascript
---begin---
function testpass() {}
---end---
```

**Comment by normful** [comment]
I'm also still seeing this with the `release` branch of coc.nvim and version 1.1.23 of coc-prettier.

**Comment by unphased** [comment]
This is kind of funny.
- I can't use a recent coc.nvim due to https://github.com/clangd/coc-clangd/issues/287 (in order to keep lsp-cxx-highlight working for the time being), and,
- I hit this quirky little behavior where it is making typescript prettier append the newline, preventing prettier from ever being happy. 

So I was like, damn this sucks for me to be wanting to use both typescript and c++ with vim. 
I dug around coc.nvim git tree around december 21st and found that the 0.80 release I'm pegging coc.nvim at is only 2 commits behind the one that introduces this fix. So I just bumped it up and sure enough, this prettier issue is fixed.

Hopefully that other issue with semantic highlights gets resolved soon so I can go back to mainline.
